package com.comtrade.constants;

public enum Type_OF_Operation_TXT {
	
	REGISTRATION_USER("REGISTRATION USER"),
	LOGIN_USER("LOGIN USER"), 
	CHANGE_PASSWORD("CHANGE PASSWORD"),
	CHECK_USER("CHECK USER"),
	CHANGE_PASSWORD_USER("CHANGE PASSWORD"),
	RETURN_USER_INFO("RETURN INFO FOR USER"),
	CHANGE_PICTURE_URL_USER("CHANGE PICTURE URL"),
	UPDATE_USER("UPDATE USER"),
	BACK_ALL_ADMINS("BACK ALL ADMINS ON PANEL"),
	DELETE_PICTURE("USER DELETE PROFILE PICTURE"),
	USER_LOGOUT("USER LOGOUT"),
	DEACTIVATE_USER("USER DEACTIVATED HIS ACCOUNT"),
	
	CHANGE_PICTURE_URL_HOTEL("CHANGE PICTURE URL FOR HOTEL"),
	REGISTRATION_NEW("REGISTRATION NEW PROPERTY"),
	REGISTRATION_USER_AND_PROPERTY("REGISTRATION USER AND PROPERTY"),
	UPDATE_PROPERTY("UPDATE PROPERTY"),
	DELETE_PICTURE_PROPERTY("DELETE PROPERTY PICTURE"),
	
	REGISTRATION_ROOM("USER REGISTRATED ROOM"), 
	UPDATE_ROOM("USER UPDATED ROOM"),
	DELETE_ROOM("DELETE ROOM"),
	
	REGISTRATION_DISCOUNT("USER REGISTRATED DISCOUNT"), 
	DELETE_DISCOUNT("USER DELETE DISCOUNT"), 
	
	REGISTRATION_RESERVATION("REGISTRATION RESERVATION"),
	DELETE_RESERVATION("CANCEL RESERVATION"),
	
	ADD_PAYMENT_CARD("USER REGISTRATED PAYMENT CARD"),
	
	ADD_RATING("USER RATE HIS RESERVATION");
	
	private String value;

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	private Type_OF_Operation_TXT(String value) {
		this.value = value;
	}
	
	
}
