package com.comtrade.constants;

public enum TransferClass_Message {
	SUCCESSFUL_REGISTRATION("SUCCESFULL REGISTRATION"),
	SUCCESSFUL_CHANGE("SUCCESFULL CHANGE"),
	SUCCESSFUL_LOGIN("SUCCESFULL LOGIN"),
	SUCCESSFUL_DELETE("SUCCESFULL DELETE"),
	
	WRONG_USERNAME_OR_PASSWORD("WRONG USERNAME OR PASSWORD"),
	EXCIST_USERNAME("USERNAME ALLREADY EXCIST"),
	EXCIST_PROPERTY("PROPERTY ALLREADY EXCIST"),
	
	RATING("YOUR RATING IS :"),
	
	EXCIST_ROOM("PROPERTY ALLREADY EXCIST"),
	ALL_FIELDS_FILL("ALL FIELDS MUST BE FILL"),
	INCORECT_ENTER_DATA("INCORRECT ENTER DATA"),
	INCORECT_ENTER_PASSWORD("INCORRECT ENTER PASSWORD"),
	INCORECT_DATE("INCORRECT DATE : ( FROM DATE > TO DATE ) "), 
	SERVER_ALLREADY_STARTED("SERVER ALLREADY STARTED"),
	RESERVED_ROOM("THIS ROOM IS RESERVED");
	
	private String value;

	private TransferClass_Message(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	
}
