package com.comtrade.constants;

public enum TransferClass_Message {
	
	SUCCESSFUL_REGISTRATION("SUCCESFULL REGISTRATION"),
	SUCCESSFUL_CHANGE("SUCCESFULL CHANGE"),
	SUCCESSFUL_LOGIN("SUCCESFULL LOGIN"),
	SUCCESSFUL_DELETE("SUCCESFULL DELETE"),
	SUCCESSFUL_RATING("THANK YOU WERY MUCH FOR RATE OUR PROPERTY!!"),
	SUCCESSFUL_FIRST_STEP("SUCCESSFULL FIRST STEP"),
	
	WRONG_USERNAME_OR_PASSWORD("WRONG USERNAME OR PASSWORD"),
	EXCIST_USERNAME("USERNAME ALLREADY EXCIST"),
	EXCIST_PROPERTY("PROPERTY ALLREADY EXCIST"),
	
	RATING("YOUR RATING IS :"),
	
	EXCIST_ROOM("PROPERTY ALLREADY EXCIST"),
	ALL_FIELDS_FILL("ALL FIELDS MUST BE FILL CORRECT"),
	
	INCORECT_ENTER_DATA("INCORRECT ENTER DATA"),
	INCORECT_ENTER_PASSWORD("INCORRECT ENTER PASSWORD"),
	INCORECT_DATE("INCORRECT DATE : ( FROM DATE > TO DATE ) "),
	INCORECT_NUMBER_BED("ADULTS + CHILDREN IS BIGGER THAN BED IN ROOM"),
	INCORECT_CARD_NUMBER("INCORECT CARD NUMBER"), 
	
	SERVER_ALLREADY_STARTED("SERVER ALLREADY STARTED"),
	RESERVED_ROOM("THIS ROOM IS RESERVED IN THAT PERIOD"), 
	DONT_DELETE_ROOM("THIS ROOM HAVE RESERVATION!!!"), 
	ACTIVATE_PAYMENT_CARD("PLEASE ACTIVATE YOUR PAYMENT METHOD"), 
	SET_DATE("YOU UST SET EXPIRATION DATE"),
	SET_CHECKIN_AND_CHCK_OUT(" YOU MUST SET CHECK IN AND CHECK OUT"),
	SELECT_ROOM("YOU MUST SELECT ROOM"), 
	RATING_NULL("RATING MUST BE GREATHER THAN NULL"), 
	SET_DATEFROM_DATETO("YOU MUST SET DATE FROM AND DATE TO"), 
	SELECT_RESERVATION("YOU MUST SELECT RESERVATION"), 
	SORRY_RESERVATION("SORRY BUT YOU DONT CANCEL YOUR RESERVATION, YOUR CHECK IN IS FOR LESS THAN 10 DAYS "),
	USER_IS_OFFLINE("SERVER : User is OFFLINE"),
	USER_DEACTIVATED("USER IS DEACTIVATED SUCCESFULLY");
	
	private String value;

	private TransferClass_Message(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	
}
