package com.comtrade.constants;

public enum Type_Of_Operation {
	
	REGISTRATION_USER, 
	LOGIN_USER, 
	CHECK_USER,
	CHANGE_PASSWORD_USER,
	RETURN_USER_INFO,
	CHANGE_PICTURE_URL_USER,
	
	
	REGISTRATION_PROPERTY, 
	BACK_ALL_ABOUT_PROPERTY,
	CHANGE_PICTURE_URL_HOTEL,
	
}
